// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: KV.proto

package kv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Val struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Val:
	//
	//	*Val_Str
	//	*Val_Num
	//	*Val_ByteArray
	Val isVal_Val `protobuf_oneof:"val"`
}

func (x *Val) Reset() {
	*x = Val{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Val) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Val) ProtoMessage() {}

func (x *Val) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Val.ProtoReflect.Descriptor instead.
func (*Val) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{0}
}

func (m *Val) GetVal() isVal_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (x *Val) GetStr() string {
	if x, ok := x.GetVal().(*Val_Str); ok {
		return x.Str
	}
	return ""
}

func (x *Val) GetNum() int64 {
	if x, ok := x.GetVal().(*Val_Num); ok {
		return x.Num
	}
	return 0
}

func (x *Val) GetByteArray() []byte {
	if x, ok := x.GetVal().(*Val_ByteArray); ok {
		return x.ByteArray
	}
	return nil
}

type isVal_Val interface {
	isVal_Val()
}

type Val_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Val_Num struct {
	Num int64 `protobuf:"varint,2,opt,name=num,proto3,oneof"`
}

type Val_ByteArray struct {
	ByteArray []byte `protobuf:"bytes,3,opt,name=byteArray,proto3,oneof"`
}

func (*Val_Str) isVal_Val() {}

func (*Val_Num) isVal_Val() {}

func (*Val_ByteArray) isVal_Val() {}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val         *Val   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	PutIfAbsent bool   `protobuf:"varint,3,opt,name=putIfAbsent,proto3" json:"putIfAbsent,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetVal() *Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *PutRequest) GetPutIfAbsent() bool {
	if x != nil {
		return x.PutIfAbsent
	}
	return false
}

type PutResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldVal *Val `protobuf:"bytes,1,opt,name=oldVal,proto3" json:"oldVal,omitempty"`
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{2}
}

func (x *PutResult) GetOldVal() *Val {
	if x != nil {
		return x.OldVal
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val *Val   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetVal() *Val {
	if x != nil {
		return x.Val
	}
	return nil
}

type SetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldValExisted bool `protobuf:"varint,1,opt,name=oldValExisted,proto3" json:"oldValExisted,omitempty"`
}

func (x *SetResult) Reset() {
	*x = SetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResult) ProtoMessage() {}

func (x *SetResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResult.ProtoReflect.Descriptor instead.
func (*SetResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{4}
}

func (x *SetResult) GetOldValExisted() bool {
	if x != nil {
		return x.OldValExisted
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MinCommitIndex int64  `protobuf:"varint,2,opt,name=minCommitIndex,proto3" json:"minCommitIndex,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetMinCommitIndex() int64 {
	if x != nil {
		return x.MinCommitIndex
	}
	return 0
}

type GetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *Val `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{6}
}

func (x *GetResult) GetVal() *Val {
	if x != nil {
		return x.Val
	}
	return nil
}

type ContainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val            *Val   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	MinCommitIndex int64  `protobuf:"varint,3,opt,name=minCommitIndex,proto3" json:"minCommitIndex,omitempty"`
}

func (x *ContainsRequest) Reset() {
	*x = ContainsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsRequest) ProtoMessage() {}

func (x *ContainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsRequest.ProtoReflect.Descriptor instead.
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{7}
}

func (x *ContainsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContainsRequest) GetVal() *Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *ContainsRequest) GetMinCommitIndex() int64 {
	if x != nil {
		return x.MinCommitIndex
	}
	return 0
}

type ContainsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ContainsResult) Reset() {
	*x = ContainsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsResult) ProtoMessage() {}

func (x *ContainsResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsResult.ProtoReflect.Descriptor instead.
func (*ContainsResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{8}
}

func (x *ContainsResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val *Val   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RemoveRequest) GetVal() *Val {
	if x != nil {
		return x.Val
	}
	return nil
}

type RemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OldVal  *Val `protobuf:"bytes,2,opt,name=oldVal,proto3" json:"oldVal,omitempty"`
}

func (x *RemoveResult) Reset() {
	*x = RemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResult) ProtoMessage() {}

func (x *RemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResult.ProtoReflect.Descriptor instead.
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveResult) GetOldVal() *Val {
	if x != nil {
		return x.OldVal
	}
	return nil
}

type ReplaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OldVal *Val   `protobuf:"bytes,2,opt,name=oldVal,proto3" json:"oldVal,omitempty"`
	NewVal *Val   `protobuf:"bytes,3,opt,name=newVal,proto3" json:"newVal,omitempty"`
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRequest.ProtoReflect.Descriptor instead.
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{13}
}

func (x *ReplaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplaceRequest) GetOldVal() *Val {
	if x != nil {
		return x.OldVal
	}
	return nil
}

func (x *ReplaceRequest) GetNewVal() *Val {
	if x != nil {
		return x.NewVal
	}
	return nil
}

type ReplaceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ReplaceResult) Reset() {
	*x = ReplaceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResult) ProtoMessage() {}

func (x *ReplaceResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceResult.ProtoReflect.Descriptor instead.
func (*ReplaceResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{14}
}

func (x *ReplaceResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinCommitIndex int64 `protobuf:"varint,1,opt,name=minCommitIndex,proto3" json:"minCommitIndex,omitempty"`
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{15}
}

func (x *SizeRequest) GetMinCommitIndex() int64 {
	if x != nil {
		return x.MinCommitIndex
	}
	return 0
}

type SizeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SizeResult) Reset() {
	*x = SizeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResult) ProtoMessage() {}

func (x *SizeResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResult.ProtoReflect.Descriptor instead.
func (*SizeResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{16}
}

func (x *SizeResult) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ClearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{17}
}

type ClearResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ClearResult) Reset() {
	*x = ClearResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResult) ProtoMessage() {}

func (x *ClearResult) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResult.ProtoReflect.Descriptor instead.
func (*ClearResult) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{18}
}

func (x *ClearResult) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type KVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitIndex int64 `protobuf:"varint,1,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	// Types that are assignable to Result:
	//
	//	*KVResponse_PutResult
	//	*KVResponse_SetResult
	//	*KVResponse_GetResult
	//	*KVResponse_ContainsResult
	//	*KVResponse_DeleteResult
	//	*KVResponse_RemoveResult
	//	*KVResponse_ReplaceResult
	//	*KVResponse_SizeResult
	//	*KVResponse_ClearResult
	Result isKVResponse_Result `protobuf_oneof:"result"`
}

func (x *KVResponse) Reset() {
	*x = KVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_KV_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVResponse) ProtoMessage() {}

func (x *KVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_KV_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVResponse.ProtoReflect.Descriptor instead.
func (*KVResponse) Descriptor() ([]byte, []int) {
	return file_KV_proto_rawDescGZIP(), []int{19}
}

func (x *KVResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (m *KVResponse) GetResult() isKVResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *KVResponse) GetPutResult() *PutResult {
	if x, ok := x.GetResult().(*KVResponse_PutResult); ok {
		return x.PutResult
	}
	return nil
}

func (x *KVResponse) GetSetResult() *SetResult {
	if x, ok := x.GetResult().(*KVResponse_SetResult); ok {
		return x.SetResult
	}
	return nil
}

func (x *KVResponse) GetGetResult() *GetResult {
	if x, ok := x.GetResult().(*KVResponse_GetResult); ok {
		return x.GetResult
	}
	return nil
}

func (x *KVResponse) GetContainsResult() *ContainsResult {
	if x, ok := x.GetResult().(*KVResponse_ContainsResult); ok {
		return x.ContainsResult
	}
	return nil
}

func (x *KVResponse) GetDeleteResult() *DeleteResult {
	if x, ok := x.GetResult().(*KVResponse_DeleteResult); ok {
		return x.DeleteResult
	}
	return nil
}

func (x *KVResponse) GetRemoveResult() *RemoveResult {
	if x, ok := x.GetResult().(*KVResponse_RemoveResult); ok {
		return x.RemoveResult
	}
	return nil
}

func (x *KVResponse) GetReplaceResult() *ReplaceResult {
	if x, ok := x.GetResult().(*KVResponse_ReplaceResult); ok {
		return x.ReplaceResult
	}
	return nil
}

func (x *KVResponse) GetSizeResult() *SizeResult {
	if x, ok := x.GetResult().(*KVResponse_SizeResult); ok {
		return x.SizeResult
	}
	return nil
}

func (x *KVResponse) GetClearResult() *ClearResult {
	if x, ok := x.GetResult().(*KVResponse_ClearResult); ok {
		return x.ClearResult
	}
	return nil
}

type isKVResponse_Result interface {
	isKVResponse_Result()
}

type KVResponse_PutResult struct {
	PutResult *PutResult `protobuf:"bytes,2,opt,name=putResult,proto3,oneof"`
}

type KVResponse_SetResult struct {
	SetResult *SetResult `protobuf:"bytes,3,opt,name=setResult,proto3,oneof"`
}

type KVResponse_GetResult struct {
	GetResult *GetResult `protobuf:"bytes,4,opt,name=getResult,proto3,oneof"`
}

type KVResponse_ContainsResult struct {
	ContainsResult *ContainsResult `protobuf:"bytes,5,opt,name=containsResult,proto3,oneof"`
}

type KVResponse_DeleteResult struct {
	DeleteResult *DeleteResult `protobuf:"bytes,6,opt,name=deleteResult,proto3,oneof"`
}

type KVResponse_RemoveResult struct {
	RemoveResult *RemoveResult `protobuf:"bytes,7,opt,name=removeResult,proto3,oneof"`
}

type KVResponse_ReplaceResult struct {
	ReplaceResult *ReplaceResult `protobuf:"bytes,8,opt,name=replaceResult,proto3,oneof"`
}

type KVResponse_SizeResult struct {
	SizeResult *SizeResult `protobuf:"bytes,9,opt,name=sizeResult,proto3,oneof"`
}

type KVResponse_ClearResult struct {
	ClearResult *ClearResult `protobuf:"bytes,10,opt,name=clearResult,proto3,oneof"`
}

func (*KVResponse_PutResult) isKVResponse_Result() {}

func (*KVResponse_SetResult) isKVResponse_Result() {}

func (*KVResponse_GetResult) isKVResponse_Result() {}

func (*KVResponse_ContainsResult) isKVResponse_Result() {}

func (*KVResponse_DeleteResult) isKVResponse_Result() {}

func (*KVResponse_RemoveResult) isKVResponse_Result() {}

func (*KVResponse_ReplaceResult) isKVResponse_Result() {}

func (*KVResponse_SizeResult) isKVResponse_Result() {}

func (*KVResponse_ClearResult) isKVResponse_Result() {}

var File_KV_proto protoreflect.FileDescriptor

var file_KV_proto_rawDesc = []byte{
	0x0a, 0x08, 0x4b, 0x56, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x69, 0x6f, 0x2e, 0x61,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x54, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x1e, 0x0a, 0x09, 0x62, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42,
	0x05, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x6d, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64,
	0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x75, 0x74, 0x49, 0x66, 0x41,
	0x62, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62,
	0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x06, 0x6f,
	0x6c, 0x64, 0x56, 0x61, 0x6c, 0x22, 0x4b, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62,
	0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x31, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x22, 0x46, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6d,
	0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x38, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x03, 0x76, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x61, 0x6c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x78, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x61, 0x6c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x69, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x28, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x0d, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e,
	0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x5b, 0x0a, 0x0c, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52,
	0x06, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x06,
	0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69,
	0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x06, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x12,
	0x31, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x56,
	0x61, 0x6c, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a,
	0x0b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xb7, 0x05, 0x0a, 0x0a, 0x4b, 0x56,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x3f, 0x0a, 0x09, 0x70, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x09, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x09,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4e, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a,
	0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64,
	0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x4b, 0x0a, 0x0d, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x42,
	0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62,
	0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x45, 0x0a, 0x0b, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6c,
	0x65, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0xd9, 0x05, 0x0a, 0x10, 0x4b, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x12,
	0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e,
	0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x69, 0x6f, 0x2e,
	0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69,
	0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b,
	0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69,
	0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4f, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x23, 0x2e, 0x69, 0x6f, 0x2e, 0x61,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x51, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x69, 0x6f,
	0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e,
	0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x2e, 0x69, 0x6f,
	0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x05, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x12, 0x22, 0x2e, 0x69, 0x6f, 0x2e, 0x61,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x69, 0x6f, 0x2e, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2e, 0x6b, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1c, 0x50, 0x01, 0x5a, 0x18, 0x69, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x72, 0x61, 0x66,
	0x74, 0x2f, 0x61, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x64, 0x62, 0x2f, 0x6b, 0x76, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_KV_proto_rawDescOnce sync.Once
	file_KV_proto_rawDescData = file_KV_proto_rawDesc
)

func file_KV_proto_rawDescGZIP() []byte {
	file_KV_proto_rawDescOnce.Do(func() {
		file_KV_proto_rawDescData = protoimpl.X.CompressGZIP(file_KV_proto_rawDescData)
	})
	return file_KV_proto_rawDescData
}

var file_KV_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_KV_proto_goTypes = []interface{}{
	(*Val)(nil),             // 0: io.afloatdb.kv.proto.Val
	(*PutRequest)(nil),      // 1: io.afloatdb.kv.proto.PutRequest
	(*PutResult)(nil),       // 2: io.afloatdb.kv.proto.PutResult
	(*SetRequest)(nil),      // 3: io.afloatdb.kv.proto.SetRequest
	(*SetResult)(nil),       // 4: io.afloatdb.kv.proto.SetResult
	(*GetRequest)(nil),      // 5: io.afloatdb.kv.proto.GetRequest
	(*GetResult)(nil),       // 6: io.afloatdb.kv.proto.GetResult
	(*ContainsRequest)(nil), // 7: io.afloatdb.kv.proto.ContainsRequest
	(*ContainsResult)(nil),  // 8: io.afloatdb.kv.proto.ContainsResult
	(*DeleteRequest)(nil),   // 9: io.afloatdb.kv.proto.DeleteRequest
	(*DeleteResult)(nil),    // 10: io.afloatdb.kv.proto.DeleteResult
	(*RemoveRequest)(nil),   // 11: io.afloatdb.kv.proto.RemoveRequest
	(*RemoveResult)(nil),    // 12: io.afloatdb.kv.proto.RemoveResult
	(*ReplaceRequest)(nil),  // 13: io.afloatdb.kv.proto.ReplaceRequest
	(*ReplaceResult)(nil),   // 14: io.afloatdb.kv.proto.ReplaceResult
	(*SizeRequest)(nil),     // 15: io.afloatdb.kv.proto.SizeRequest
	(*SizeResult)(nil),      // 16: io.afloatdb.kv.proto.SizeResult
	(*ClearRequest)(nil),    // 17: io.afloatdb.kv.proto.ClearRequest
	(*ClearResult)(nil),     // 18: io.afloatdb.kv.proto.ClearResult
	(*KVResponse)(nil),      // 19: io.afloatdb.kv.proto.KVResponse
}
var file_KV_proto_depIdxs = []int32{
	0,  // 0: io.afloatdb.kv.proto.PutRequest.val:type_name -> io.afloatdb.kv.proto.Val
	0,  // 1: io.afloatdb.kv.proto.PutResult.oldVal:type_name -> io.afloatdb.kv.proto.Val
	0,  // 2: io.afloatdb.kv.proto.SetRequest.val:type_name -> io.afloatdb.kv.proto.Val
	0,  // 3: io.afloatdb.kv.proto.GetResult.val:type_name -> io.afloatdb.kv.proto.Val
	0,  // 4: io.afloatdb.kv.proto.ContainsRequest.val:type_name -> io.afloatdb.kv.proto.Val
	0,  // 5: io.afloatdb.kv.proto.RemoveRequest.val:type_name -> io.afloatdb.kv.proto.Val
	0,  // 6: io.afloatdb.kv.proto.RemoveResult.oldVal:type_name -> io.afloatdb.kv.proto.Val
	0,  // 7: io.afloatdb.kv.proto.ReplaceRequest.oldVal:type_name -> io.afloatdb.kv.proto.Val
	0,  // 8: io.afloatdb.kv.proto.ReplaceRequest.newVal:type_name -> io.afloatdb.kv.proto.Val
	2,  // 9: io.afloatdb.kv.proto.KVResponse.putResult:type_name -> io.afloatdb.kv.proto.PutResult
	4,  // 10: io.afloatdb.kv.proto.KVResponse.setResult:type_name -> io.afloatdb.kv.proto.SetResult
	6,  // 11: io.afloatdb.kv.proto.KVResponse.getResult:type_name -> io.afloatdb.kv.proto.GetResult
	8,  // 12: io.afloatdb.kv.proto.KVResponse.containsResult:type_name -> io.afloatdb.kv.proto.ContainsResult
	10, // 13: io.afloatdb.kv.proto.KVResponse.deleteResult:type_name -> io.afloatdb.kv.proto.DeleteResult
	12, // 14: io.afloatdb.kv.proto.KVResponse.removeResult:type_name -> io.afloatdb.kv.proto.RemoveResult
	14, // 15: io.afloatdb.kv.proto.KVResponse.replaceResult:type_name -> io.afloatdb.kv.proto.ReplaceResult
	16, // 16: io.afloatdb.kv.proto.KVResponse.sizeResult:type_name -> io.afloatdb.kv.proto.SizeResult
	18, // 17: io.afloatdb.kv.proto.KVResponse.clearResult:type_name -> io.afloatdb.kv.proto.ClearResult
	1,  // 18: io.afloatdb.kv.proto.KVRequestHandler.put:input_type -> io.afloatdb.kv.proto.PutRequest
	3,  // 19: io.afloatdb.kv.proto.KVRequestHandler.set:input_type -> io.afloatdb.kv.proto.SetRequest
	5,  // 20: io.afloatdb.kv.proto.KVRequestHandler.get:input_type -> io.afloatdb.kv.proto.GetRequest
	7,  // 21: io.afloatdb.kv.proto.KVRequestHandler.contains:input_type -> io.afloatdb.kv.proto.ContainsRequest
	9,  // 22: io.afloatdb.kv.proto.KVRequestHandler.delete:input_type -> io.afloatdb.kv.proto.DeleteRequest
	11, // 23: io.afloatdb.kv.proto.KVRequestHandler.remove:input_type -> io.afloatdb.kv.proto.RemoveRequest
	13, // 24: io.afloatdb.kv.proto.KVRequestHandler.replace:input_type -> io.afloatdb.kv.proto.ReplaceRequest
	15, // 25: io.afloatdb.kv.proto.KVRequestHandler.size:input_type -> io.afloatdb.kv.proto.SizeRequest
	17, // 26: io.afloatdb.kv.proto.KVRequestHandler.clear:input_type -> io.afloatdb.kv.proto.ClearRequest
	19, // 27: io.afloatdb.kv.proto.KVRequestHandler.put:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 28: io.afloatdb.kv.proto.KVRequestHandler.set:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 29: io.afloatdb.kv.proto.KVRequestHandler.get:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 30: io.afloatdb.kv.proto.KVRequestHandler.contains:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 31: io.afloatdb.kv.proto.KVRequestHandler.delete:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 32: io.afloatdb.kv.proto.KVRequestHandler.remove:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 33: io.afloatdb.kv.proto.KVRequestHandler.replace:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 34: io.afloatdb.kv.proto.KVRequestHandler.size:output_type -> io.afloatdb.kv.proto.KVResponse
	19, // 35: io.afloatdb.kv.proto.KVRequestHandler.clear:output_type -> io.afloatdb.kv.proto.KVResponse
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_KV_proto_init() }
func file_KV_proto_init() {
	if File_KV_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_KV_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Val); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_KV_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_KV_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Val_Str)(nil),
		(*Val_Num)(nil),
		(*Val_ByteArray)(nil),
	}
	file_KV_proto_msgTypes[19].OneofWrappers = []interface{}{
		(*KVResponse_PutResult)(nil),
		(*KVResponse_SetResult)(nil),
		(*KVResponse_GetResult)(nil),
		(*KVResponse_ContainsResult)(nil),
		(*KVResponse_DeleteResult)(nil),
		(*KVResponse_RemoveResult)(nil),
		(*KVResponse_ReplaceResult)(nil),
		(*KVResponse_SizeResult)(nil),
		(*KVResponse_ClearResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_KV_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_KV_proto_goTypes,
		DependencyIndexes: file_KV_proto_depIdxs,
		MessageInfos:      file_KV_proto_msgTypes,
	}.Build()
	File_KV_proto = out.File
	file_KV_proto_rawDesc = nil
	file_KV_proto_goTypes = nil
	file_KV_proto_depIdxs = nil
}
